In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# download data set: https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
# info: https://archive.ics.uci.edu/ml/datasets/banknote+authentication

# load data
bankdata = pd.read_csv("/Users/mallampati/Downloads/bill_authentication.csv")

In [2]:
# see the data
bankdata.shape

(1372, 5)

In [3]:
# see head
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
# data processing
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class']

In [5]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [6]:
# train the SVM
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [7]:
# predictions
y_pred = svclassifier.predict(X_test)

In [8]:
# Evaluate model
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))

[[163   1]
 [  1 110]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       164
           1       0.99      0.99      0.99       111

   micro avg       0.99      0.99      0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [12]:
# Iris dataset  https://archive.ics.uci.edu/ml/datasets/iris4
def eval_iris():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

    # Assign colum names to the dataset
    colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

    # Read dataset to pandas dataframe
    irisdata = pd.read_csv(url, names=colnames) 

    # process
    X = irisdata.drop('Class', axis=1)  
    y = irisdata['Class']  

    # train
    from sklearn.model_selection import train_test_split  
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

    # TODO: Evaluates perfomance of Polynomial Kernel, Gaussian Kernel, and Sigmoid Kernel. TRAIN & PRINT EVALUATION SCORES
    
    # Polynomial Kernel
    from sklearn.svm import SVC  
    polyker = SVC(kernel='poly', degree=8)  
    polyker.fit(X_train, y_train)
    
    y_pred = polyker.predict(X_test)  
    
    from sklearn.metrics import classification_report, confusion_matrix 
    print('Polynomial Kernel' + '\n')
    print(confusion_matrix(y_test, y_pred))  
    print(classification_report(y_test, y_pred))
    
    # Gaussian Kernel 
    gaussker = SVC(kernel='rbf')  
    gaussker.fit(X_train, y_train)
    
    y_pred2 = gaussker.predict(X_test) 
     
    print('\n' + 'Gaussian Kernel' + '\n')
    print(confusion_matrix(y_test, y_pred2))  
    print(classification_report(y_test, y_pred2)) 
    
    # Sigmoid Kernel
    sigker = SVC(kernel='sigmoid')  
    sigker.fit(X_train, y_train)
    
    y_pred3 = sigker.predict(X_test)
    
    print('\n' + 'Sigmoid Kernel' + '\n')
    print(confusion_matrix(y_test, y_pred3))  
    print(classification_report(y_test, y_pred3)) 

In [13]:
eval_iris()

/Users/mallampati/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Polynomial Kernel

[[ 9  0  0]
 [ 0  8  1]
 [ 0  2 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.80      0.89      0.84         9
 Iris-virginica       0.91      0.83      0.87        12

      micro avg       0.90      0.90      0.90        30
      macro avg       0.90      0.91      0.90        30
   weighted avg       0.90      0.90      0.90        30


Gaussian Kernel

[[ 9  0  0]
 [ 0  7  2]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       1.00      0.78      0.88         9
 Iris-virginica       0.86      1.00      0.92        12

      micro avg       0.93      0.93      0.93        30
      macro avg       0.95      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30


Sigmoid Kernel

[[ 7  2  0]
 [ 8  1  0]
 [12  0  0]]
                 precision    r

/Users/mallampati/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/mallampati/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/Users/mallampati/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
